finance_tracker/budgets/urls.py
from django.urls import path

from budgets.views import budget_overview, delete_budget

app_name = 'budgets'

urlpatterns = [
    path('', budget_overview, name='budget_overview'),
    path('delete-budget/<int:budget_id>/', delete_budget, name='delete_budget'),
]

finance_tracker/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
]

finance_tracker/budgets/models.py
from django.db import models
from transactions.models import Category
from django.contrib.auth import get_user_model

User = get_user_model()

class CategoryBudget(models.Model):
    user = models.ManyToManyField(User) 
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    budget_limit = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        user_names = ', '.join([user.username for user in self.user.all()])
        return f'{user_names} - {self.category.name}'
    

class CustomBudgetAlert(models.Model):
    message = models.CharField(max_length=200)
    budget = models.ForeignKey('CategoryBudget', on_delete=models.CASCADE, related_name='custom_alerts')
    threshold = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return self.message

finance_tracker/budgets/forms.py
from django import forms
from transactions.models import Category

class CategoryBudgetForm(forms.Form):
    category = forms.ModelChoiceField(queryset=None)
    budget_limit = forms.DecimalField(min_value=0)

    def __init__(self, user, category_type, *args, **kwargs):
        super(CategoryBudgetForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.filter(user=user, type=category_type)

finance_tracker/budgets/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Sum
from .forms import CategoryBudgetForm
from .models import CategoryBudget
from transactions.models import Transaction, Category
from django.http import HttpResponse


def budget_overview(request):
    try:
        # Retrieve all transactions for the current user
        transactions = Transaction.objects.filter(user=request.user).select_related('category')

        # Calculate the total income and expenses
        total_income = transactions.filter(category__type='income').aggregate(total_income=Sum('amount'))['total_income'] or 0
        total_expenses = transactions.filter(category__type='expense').aggregate(total_expenses=Sum('amount'))['total_expenses'] or 0

        # Handle cases where the sums are None (no transactions or no amounts)
        total_income = total_income or 0
        total_expenses = total_expenses or 0

        # Calculate the current balance
        current_balance = (total_income or 0) - (total_expenses or 0)
        current_balance = current_balance if current_balance is not None else 0

        # Retrieve categories belonging to the user
        categories = Category.objects.filter(user=request.user, type=Category.EXPENSE).prefetch_related('categorybudget_set')

        # Get currency
        user_currency = "$"

        # Get the budget limits and expenses for each category
        category_budgets = {}
        for category in categories:
            category_expenses = transactions.filter(category=category).aggregate(Sum('amount'))['amount__sum'] or 0
            try:
                category_budget = CategoryBudget.objects.get(category=category, user=request.user)
                remaining_budget = category_budget.budget_limit - category_expenses
            except CategoryBudget.DoesNotExist:
                category_budget = None
                remaining_budget = None
            category_budgets[category.name] = {
                'id': category_budget.id if category_budget else None,
                'budget_limit': category_budget.budget_limit if category_budget and category_budget.budget_limit is not None else 0,
                'remaining_budget': remaining_budget if remaining_budget is not None else 0,
                'amount_spent': category_expenses or 0,
                'currency': user_currency
            }

        if request.method == 'POST':
            form = CategoryBudgetForm(request.user, category_type=Category.EXPENSE, data=request.POST)
            if form.is_valid():
                category = form.cleaned_data['category']
                budget_limit = form.cleaned_data['budget_limit']
                CategoryBudget.objects.update_or_create(category=category, user=request.user, defaults={'budget_limit': budget_limit})
                return redirect('budgets:budget_overview')
            else:
                # Handle form validation errors
                error_message = "Invalid form data."
        else:
            form = CategoryBudgetForm(request.user, category_type=Category.EXPENSE)

        context = {
            'total_income': total_income,
            'total_expenses': total_expenses,
            'current_balance': current_balance,
            'category_budgets': category_budgets,
            'form': form,
            'user_currency': user_currency,
            'categories': categories
        }

        return render(request, 'budgets/overview.html', context)
    except Exception as e:
        # Handle unexpected exceptions
        error_message = str(e)
        return HttpResponse(f'error_message : {error_message}')

def delete_budget(request, budget_id):
    try:
        budget = get_object_or_404(CategoryBudget, id=budget_id)
        budget.delete()
        return redirect('budgets:budget_overview')
    except Exception as e:
        # Handle unexpected exceptions
        error_message = str(e)
        return HttpResponse(f'error_message : {error_message}')

finance_tracker/budgets/templates/budgets/overview.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Income</h5>
                    <p class="card-text amount">{{ user_currency }}{{ total_income }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Total Expenses</h5>
                    <p class="card-text amount">{{ user_currency }}{{ total_expenses }}</p>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Current Balance</h5>
                    <p class="card-text amount">{{ user_currency }}{{ current_balance }}</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <h2>Category Budgets</h2>
            <div class="card">
                <ul class="list-group list-group-flush">
                    {% for category, budget in category_budgets.items %}
                        <li class="list-group-item">
                            {{ category }} - Budget Limit: {{ budget.currency }}{{ budget.budget_limit }}  | Remaining Budget: {{ budget.currency }}{{ budget.remaining_budget }} | Amount Spent: {{ budget.currency }}{{ budget.amount_spent }}
                            {% if budget.id %}
                                <form method="POST" action="{% url 'budgets:delete_budget' budget_id=budget.id %}" style="display: inline;">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                <div class="card-body">
                    <button id="toggle-form-btn" class="btn btn-primary">Add/Edit Budget Limit</button>
                </div>
            </div>
        </div>
    </div>

    <div id="budget-form-wrapper" style="display: none;">
        <form method="POST" action="{% url 'budgets:budget_overview' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
    <script src="{% static 'js/budget_form_toggle.js' %}"></script>
{% endblock %}