finance_tracker/core/urls.py
from django.contrib import admin
from django.urls import path
from core.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home, name='home'),
]

finance_tracker/transactions/urls.py
from django.urls import path
from . import views

app_name = "transactions"

urlpatterns = [
    path("add/", views.add_transaction, name="add_transaction"),
    path(
        "<int:transaction_id>/delete/",
        views.delete_transaction,
        name="delete_transaction",
    ),
    path("categories/", views.categories_view, name="categories"),
    path(
        "manage-categories/", views.manage_categories, name="manage_categories"
    ),
    path(
        "categories/<int:category_id>/delete/",
        views.delete_category,
        name="delete_category",
    ),
    path("", views.transaction_list, name="transaction_list"),
    path("<int:pk>/", views.transaction_detail, name="transaction_detail"),
]

finance_tracker/transactions/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    EXPENSE = 'expense'
    INCOME = 'income'
    SAVING = 'saving'
    INVESTMENT = 'investment'
    
    CATEGORY_TYPES = [
        (EXPENSE, 'Expense'),
        (INCOME, 'Income'),
        (SAVING, 'Saving'),
        (INVESTMENT, 'Investment'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    type = models.CharField(max_length=10, choices=CATEGORY_TYPES)
    parent_category = models.ForeignKey('self', on_delete=models.SET_NULL, blank=True, null=True, related_name='subcategories')

    class Meta:
        unique_together = ('user', 'name')

    def __str__(self):
        return self.name


class RecurringTransaction(models.Model):
    FREQUENCY_CHOICES = [
        ('daily', 'Daily'),
        ('weekly', 'Weekly'),
        ('monthly', 'Monthly'),
        ('yearly', 'Yearly'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    frequency = models.CharField(max_length=10, choices=FREQUENCY_CHOICES)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"Recurring Transaction {self.id}"


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = models.CharField(max_length=255, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(default=timezone.now)
    parent_transaction = models.ForeignKey('self', null=True, blank=True, on_delete=models.SET_NULL, related_name='sub_transactions')
    recurring_transaction = models.ForeignKey(RecurringTransaction, on_delete=models.CASCADE, null=True, blank=True)
    currency = models.CharField(choices=settings.CURRENCIES.items(), default='USD', max_length=3)

    def __str__(self):
        return f"Transaction {self.id}"


class TransactionSplit(models.Model):
    REQUEST_STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('accepted', 'Accepted'),
        ('declined', 'Declined')
    ]
    requester = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transaction_splits_made')
    requestee = models.ForeignKey(User, on_delete=models.CASCADE, related_name='transaction_splits_received')
    transaction = models.ForeignKey(Transaction, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(choices=REQUEST_STATUS_CHOICES, default='pending', max_length=10)

finance_tracker/transactions/forms.py
from django import forms
from tempus_dominus.widgets import DateTimePicker
from .models import Transaction, Category

class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ['title', 'description', 'amount', 'category', 'date']
        widgets = {
            'date': DateTimePicker(
                options={
                    'useCurrent': True,
                    'format': 'YYYY-MM-DD HH:mm',
                },
                attrs={
                    'append': 'fa fa-calendar',
                }
            ),
        }

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'type']

finance_tracker/transactions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.http import HttpResponseForbidden
from .models import Transaction
from .models import Category
from .forms import CategoryForm, TransactionForm
from django.db.models import Q
from datetime import datetime
from django.http import JsonResponse
from transactions.utils import CategoryEncoder
from django.core import serializers
import logging

# Set up a specific logger with our desired output level
logger = logging.getLogger(__name__)


@login_required
def add_transaction(request):
    if request.method == "POST":
        form = TransactionForm(request.POST)
        if form.is_valid():
            try:
                transaction = form.save(commit=False)
                transaction.user = request.user
                transaction.save()
                logger.info(
                    "Transaction added successfully by user: %s",
                    request.user.username,
                )
                return redirect("users:dashboard")
            except Exception as e:
                error_message = str(e)
                logger.error(
                    "Error adding transaction by user %s: %s",
                    request.user.username,
                    error_message,
                )
        else:
            error_message = "Invalid form submission."
            logger.warning(
                "Invalid transaction form submission by user: %s",
                request.user.username,
            )
    else:
        form = TransactionForm()
        error_message = None

    return render(
        request,
        "transactions/add_transaction.html",
        {"form": form, "error_message": error_message},
    )


@login_required
@require_POST
def delete_transaction(request, transaction_id):
    try:
        # Get the transaction object
        transaction = get_object_or_404(Transaction, id=transaction_id)

        # Check if the transaction belongs to the current user
        if transaction.user != request.user:
            logger.warning(
                "User %s tried to delete transaction not owned by them: %s",
                request.user.username,
                transaction_id,
            )
            return HttpResponseForbidden(
                "You don't have permission to delete this transaction."
            )

        # Perform the delete operation
        transaction.delete()
        logger.info(
            "Transaction deleted successfully by user: %s",
            request.user.username,
        )

        # Redirect to the dashboard or any other appropriate page
        return redirect("users:dashboard")
    except Exception as e:
        error_message = str(e)
        logger.error(
            "Error deleting transaction (ID: %s) by user %s: %s",
            transaction_id,
            request.user.username,
            error_message,
        )
        return render(request, "error.html", {"error_message": error_message})


@login_required
def categories_view(request):
    try:
        categories = Category.objects.all()
        categories_data = serializers.serialize("json", categories)

        response_data = {
            "categories": categories_data,
        }

        return JsonResponse(response_data, safe=False)
    except Exception as e:
        error_message = str(e)
        logger.error(
            "Error retrieving categories by user %s: %s",
            request.user.username,
            error_message,
        )
        return render(request, "error.html", {"error_message": error_message})


@login_required
def manage_categories(request):
    try:
        categories = Category.objects.filter(user=request.user)
        form = CategoryForm()

        if request.method == "POST":
            form = CategoryForm(request.POST)
            if form.is_valid():
                category = form.save(commit=False)
                category.user = request.user
                category.save()
                logger.info(
                    "Category added successfully by user: %s",
                    request.user.username,
                )
                return redirect("transactions:manage_categories")
            else:
                logger.warning(
                    "Invalid category form submission by user: %s",
                    request.user.username,
                )

        context = {"categories": categories, "form": form}
        return render(request, "transactions/manage_categories.html", context)
    except Exception as e:
        error_message = str(e)
        logger.error(
            "Error managing categories by user %s: %s",
            request.user.username,
            error_message,
        )
        return render(request, "error.html", {"error_message": error_message})


@login_required
@require_POST
def delete_category(request, category_id):
    try:
        category = get_object_or_404(
            Category, pk=category_id, user=request.user
        )
        category.delete()
        logger.info(
            "Category (ID: %s) deleted successfully by user: %s",
            category_id,
            request.user.username,
        )
        return redirect("transactions:manage_categories")
    except Exception as e:
        error_message = str(e)
        logger.error(
            "Error deleting category (ID: %s) by user %s: %s",
            category_id,
            request.user.username,
            error_message,
        )
        return render(request, "error.html", {"error_message": error_message})


@login_required
def transaction_list(request):
    try:
        # Fetch all transactions for the current user
        user = request.user
        transactions = Transaction.objects.filter(
            user=user, parent_transaction=None
        )

        # Get the sort_by, filter_by, sort_order, and filter_value from the request's GET parameters
        sort_by = request.GET.get(
            "sort_field", "date"
        )  # Default to sorting by date
        filter_by = request.GET.get("filter_by", "")
        sort_order = request.GET.get(
            "sort_order", "asc"
        )  # Default to ascending order
        filter_value = request.GET.get("filter_value", "")

        lookup_mapping = {
            "category": "category__name__icontains",
            "title": "title__icontains",
            "description": "description__icontains",
            "amount": "amount",
            "date": "date",
            "field_name": "field_name__icontains",
        }

        if filter_by and filter_value:
            lookup_field = lookup_mapping.get(filter_by)
            if lookup_field:
                if filter_by == "date":
                    filter_value = datetime.strptime(
                        filter_value, "%Y-%m-%d"
                    ).date()
                transactions = transactions.filter(
                    **{lookup_field: filter_value}
                )
                logger.info(
                    f"Applied filter {filter_by} with value {filter_value} for user {user.username}"
                )

        categories = transactions.values_list(
            "category__name", flat=True
        ).distinct()

        if sort_by:
            if sort_order == "asc":
                transactions = transactions.order_by(sort_by)
            else:
                transactions = transactions.order_by(f"-{sort_by}")
            logger.info(
                f"Sorted transactions by {sort_by} in {sort_order} order for user {user.username}"
            )

        if request.method == "POST":
            form = TransactionForm(request.POST)
            if form.is_valid():
                try:
                    transaction = form.save(commit=False)
                    transaction.user = request.user
                    transaction.save()
                    logger.info(
                        f"Transaction added successfully by user {user.username}"
                    )
                    return redirect("transactions:transaction_list")
                except Exception as e:
                    error_message = str(e)
                    logger.error(
                        f"Error while saving transaction by user {user.username}: {error_message}"
                    )
            else:
                error_message = "Invalid form submission."
                logger.warning(
                    f"Invalid transaction form submission by user {user.username}"
                )
        else:
            form = TransactionForm()

        context = {
            "transactions": transactions,
            "categories": categories,
            "form": form,
        }
        return render(request, "transactions/transaction_list.html", context)

    except Exception as e:
        error_message = str(e)
        logger.error(
            f"General error in transaction_list view for user {request.user.username}: {error_message}"
        )
        return render(request, "error.html", {"error_message": error_message})


@login_required
def transaction_detail(request, pk):
    try:
        transaction = get_object_or_404(Transaction, pk=pk)
        logger.info(
            f"Retrieved transaction with ID {pk} for user {request.user.username}"
        )

        transactions = Transaction.objects.filter(parent_transaction_id=pk)

        if request.method == "POST":
            subtransaction_form = TransactionForm(request.POST)
            if subtransaction_form.is_valid():
                try:
                    subtransaction = subtransaction_form.save(commit=False)
                    subtransaction.user = request.user
                    subtransaction.parent_transaction = transaction

                    allowed_categories = Category.objects.filter(
                        Q(user=request.user)
                        & (

finance_tracker/transactions/templates/transactions/add_transaction.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <div class="container">
    <h2>Add Transaction</h2>

    <form method="POST">
      {% csrf_token %}
      {{ form|crispy }}
      {% if form.errors %}
      <div class="alert alert-danger">
        <strong>Error:</strong>
        <ul>
          {% for field_errors in form.errors %}
            {% for error in field_errors %}
              <li>{{ error_message }}</li>
            {% endfor %}
          {% endfor %}
        </ul>
      </div>
    {% endif %}
      <button type="submit" class="btn btn-primary">Add</button>
    </form>
  </div>
{% endblock %}

finance_tracker/transactions/templates/transactions/categories.html
{}

finance_tracker/transactions/templates/transactions/manage_categories.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h2>Manage Categories</h2>

  <form method="POST" class="category-form">
    {% csrf_token %}
    {{ form|crispy }}

    <button type="submit" class="btn btn-primary">Add Category</button>
  </form>

  <h3>Categories</h3>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Type</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      {% for category in categories %}
        <tr>
          <td>{{ category.name }}</td>
          <td>{{ category.get_type_display }}</td>
          <td>
            <form method="POST" action="{% url 'transactions:delete_category' category.pk %}">
              {% csrf_token %}
              <button type="submit" class="btn btn-danger btn-sm">Delete</button>
            </form>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

finance_tracker/transactions/templates/transactions/transaction_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <h1>Transaction Detail</h1>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ transaction.title }}</h5>
        <p class="card-text">{{ transaction.description }}</p>
        <p class="card-text">Amount: {{ transaction.amount }}</p>
        <p class="card-text">Category: {{ transaction.category }}</p>
        <p class="card-text">Date: {{ transaction.date }}</p>
        
        {% if transaction.parent_transaction %}
          <a href="{% url 'transactions:transaction_detail' transaction.parent_transaction.id %}" class="btn btn-primary">Back to Parent Transaction</a>
        {% else %}
          <a href="{% url 'transactions:transaction_list' %}" class="btn btn-primary">Back to List</a>
        {% endif %}
      </div>
    </div>
    <tr>
      <td colspan="6">
          <button id="add-transaction-btn" class="btn btn-primary">Add Transaction</button>
          <div id="add-transaction-form" style="display: none;">
              <h3>Add Transaction</h3>
              <form id="addTransactionForm" method="POST" class="add-transaction-form">
                  {% csrf_token %}
                  {{ subtransaction_form.as_p }}
                  <button type="submit" class="btn btn-primary">Add</button>
              </form>
          </div>
      </td>
    </tr>
    {% if transactions %}
    <div class="table-responsive">
        <table class="table table-striped transactions-table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" class="sortable" data-sort-field="category">
                        <button type="button" class="btn btn-light header-button">
                            Actions <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="date">
                        <button type="button" class="btn btn-light header-button">
                            Date <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="title">
                        <button type="button" class="btn btn-light header-button">
                            Title <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="description">
                        <button type="button" class="btn btn-light header-button">
                            Description <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="amount">
                        <button type="button" class="btn btn-light header-button">
                            Amount <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="category">
                        <button type="button" class="btn btn-light header-button">
                            Category <i class="fas fa-sort"></i>
                        </button>
                    </th>
                </tr>                
            </thead>
            <tbody id="transaction-table-body">
                {% csrf_token %}
                {% include 'transactions/transaction_table.html' %}
            </tbody>
        </table>
    </div>
    {% endif %}
  </div>
{% endblock %}

{% block scripts %}
  <script src="{% static 'js/delete_transaction.js' %}"></script>
  <script src="{% static 'js/add_transaction.js' %}"></script>
{% endblock %}

finance_tracker/transactions/templates/transactions/transaction_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% block head %}
        <link rel="stylesheet" href="{% static 'css/table.css' %}">
        <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    {% endblock %}
    <h1>Transaction List</h1>
    <tr>
        <td colspan="6">
            <button id="add-transaction-btn" class="btn btn-primary">Add Transaction</button>
            <div id="add-transaction-form" style="display: none;">
                <h3>Add Transaction</h3>
                <form id="addTransactionForm" method="POST" class="add-transaction-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Add</button>
                </form>
            </div>
        </td>
    </tr>
    <form id="transaction-filter-form" method="GET" action="{% url 'transactions:transaction_list' %}">
        <div class="form-row">
            <div class="form-group col-md-4">
                <label for="filter_by">Filter By:</label>
                <select id="filter_by" class="form-control" name="filter_by">
                    <option value="none">None</option>
                    <option value="amount">Amount</option>
                    <option value="date">Date</option>
                    <option value="category">Category</option>
                    <!-- Add more options for other fields as needed -->
                </select>
            </div>
            <div class="form-group col-md-8" id="filter_value_wrapper">
                <label for="filter_value" id="filter_value_label">Filter Value:</label>
                <input type="text" id="filter_value" class="form-control" name="filter_value">
                <select id="category-filter" class="form-control" name="category_filter" style="display: none;">
                    <!-- Populate the dropdown options with categories from the backend -->
                    {% for category_name in categories %}
                        <option value="{{ category_name }}">{{ category_name }}</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <input type="hidden" id="filter_by_preserved" name="filter_by" value="">
        <input type="hidden" id="filter_value_preserved" name="filter_value" value="">
        <button type="submit" class="btn btn-primary">Apply Filters</button>
    </form>
    
  

    <div class="table-responsive">
        <table class="table table-striped transactions-table table-hover">
            <thead class="thead-dark">
                <tr>
                    <th scope="col" class="sortable" data-sort-field="category">
                        <button type="button" class="btn btn-light header-button">
                            Actions <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="date">
                        <button type="button" class="btn btn-light header-button">
                            Date <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="title">
                        <button type="button" class="btn btn-light header-button">
                            Title <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="description">
                        <button type="button" class="btn btn-light header-button">
                            Description <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="amount">
                        <button type="button" class="btn btn-light header-button">
                            Amount <i class="fas fa-sort"></i>
                        </button>
                    </th>
                    <th scope="col" class="sortable" data-sort-field="category">
                        <button type="button" class="btn btn-light header-button">
                            Category <i class="fas fa-sort"></i>
                        </button>
                    </th>
                </tr>                
            </thead>
            <tbody id="transaction-table-body">
                {% csrf_token %}
                {% include 'transactions/transaction_table.html' %}
            </tbody>
        </table>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static 'js/transaction_filtering.js' %}"></script>
    <script src="{% static 'js/delete_transaction.js' %}"></script>
    <script src="{% static 'js/add_transaction.js' %}"></script>
{% endblock %}

finance_tracker/transactions/templates/transactions/transaction_table.html
{% if transactions.exists %}
    {% for transaction in transactions %}
    <tr class="parent-row">
        <td>
            <button class="btn btn-danger delete-transaction-btn" data-transaction-id="{{ transaction.id }}">Delete</button>
            <a class="btn btn-primary" href="{% url 'transactions:transaction_detail' transaction.id %}">View Details</a>
        </td>
        <td>{{ transaction.date }}</td>
        <td>{{ transaction.title }}</td>
        <td>{{ transaction.description }}</td>
        <td>{{ transaction.amount }}</td>
        <td>{{ transaction.category }}</td>
    </tr>
    {% endfor %}
{% else %}
    <tr>
        <td colspan="6">No transactions found.</td>
    </tr>
{% endif %}